export * from "./names.js";

/** @deprecated Use `ParseError` and `ResourceError`. */
export { A2uiParseError, A2uiResourceError } from "./errors.js";
/** @deprecated Use `MIME_TYPE` and `ResourceReader`. */
export { A2UI_MIME_TYPE, type A2uiResourceReader } from "./mime.js";
/** @deprecated Use `MCP_SCHEMA_REVISION`. */
export { A2UI_MCP_SCHEMA_REVISION } from "./schema-revision.js";
/** @deprecated Use the concise `MCP_*`, `isMcpBindingGrant`, and `negotiateMcpBinding` names. */
export {
  A2UI_MCP_BINDING_VERSION,
  A2UI_MCP_EXTENSION_CAPABILITIES,
  A2UI_MCP_EXTENSION_ID,
  A2UI_MCP_PROTOCOL_VERSION,
  A2UI_MCP_TRANSPORT,
  isA2uiMcpBindingGrant,
  negotiateA2uiMcpBinding,
} from "./binding.js";
/** @deprecated Use `McpBindingGrant` and `McpBindingNegotiation`. */
export type { A2uiMcpBindingGrant, A2uiMcpBindingNegotiation } from "./binding.js";
/** @deprecated Use the corresponding concise package export without the `A2uiV1` prefix. */
export {
  A2UI_V1_MAX_ENVELOPES,
  A2UI_V1_MAX_SOURCE_LENGTH,
  A2UI_V1_MAX_STORE_STRING_CODE_UNITS,
  A2UI_V1_MAX_STORE_VALUES,
  A2UI_V1_PROTOCOL_VERSION,
  A2UI_V1_BASIC_CATALOG_ID,
  A2UI_V1_BASIC_COMPONENT_NAMES,
  A2UI_V1_BASIC_FUNCTION_NAMES,
  A2UI_V1_SYSTEM_FUNCTION_NAMES,
  A2UI_V1_HOST_EXTENSION_MAX_EVENTS,
  A2UI_V1_HOST_EXTENSION_MAX_INSTANCES,
  A2UI_V1_HOST_EXTENSION_MAX_MANIFESTS,
  A2UI_V1_HOST_EXTENSION_MAX_NEEDS,
  A2UI_V1_HOST_EXTENSION_MAX_UPDATES,
  A2UI_V1_HOST_EXTENSION_PROFILE_ID,
  A2UI_V1_HOST_EXTENSION_PROFILE_VERSION,
  A2UI_V1_MAX_COMPONENTS,
  A2UI_V1_MAX_SURFACES,
  A2uiSurfaceStore,
  createA2uiV1ActionDeliveryHandler,
  createA2uiV1ActionEnvelope,
  createA2uiV1BasicCatalogPolicy,
  createA2uiV1HostExtensionCapabilitySettings,
  createA2uiV1HostExtensionRegistry,
  createA2uiV1RendererCapabilities,
  evaluateA2uiV1FormatString,
  negotiateA2uiV1Capabilities,
  negotiateA2uiV1HostExtensions,
  parseA2uiV1AgentCapabilities,
  parseA2uiV1Envelope,
  parseA2uiV1Jsonl,
  parseA2uiV1HostExtensionCapabilityValue,
  parseA2uiV1HostExtensionManifest,
  parseA2uiV1RendererCapabilities,
  parseA2uiV1RendererToAgentEnvelope,
  resolveA2uiV1JsonlFromToolResult,
  getA2uiV1HostExtensionManifest,
  getA2uiV1HostExtensionCatalogIds,
  getA2uiV1HostExtensionManifestFingerprint,
  isA2uiV1HostExtensionRegistry,
  validateA2uiV1HostExtensionComponent,
  validateA2uiV1HostExtensionEvent,
  validateA2uiV1SurfaceState,
} from "./v1/index.js";
/** @deprecated Use the corresponding concise package type without the `A2uiV1` prefix. */
export type {
  A2uiV1ActionDeliveryHandler,
  A2uiV1ActionDeliveryOptions,
  A2uiV1ActionDeliveryPolicy,
  A2uiV1Action,
  A2uiV1ActionEnvelope,
  A2uiV1ActionEnvelopeInput,
  A2uiV1AgentCapabilities,
  A2uiV1BasicCatalogPolicyOptions,
  A2uiV1CallAgentFunctionEnvelope,
  A2uiV1CapabilityNegotiation,
  A2uiV1Component,
  A2uiV1CreateSurfaceEnvelope,
  A2uiV1DeleteSurfaceEnvelope,
  A2uiV1ErrorEnvelope,
  A2uiV1Envelope,
  A2uiV1EnvelopeKind,
  A2uiV1FormatStringExpressionBudgetConsumer,
  A2uiV1FormatStringExpressionResolver,
  A2uiV1HostExtensionCapabilityEntry,
  A2uiV1HostExtensionCapabilitySettings,
  A2uiV1HostExtensionEventManifest,
  A2uiV1HostExtensionManifest,
  A2uiV1HostExtensionNegotiation,
  A2uiV1HostExtensionRegistry,
  A2uiV1HostExtensionRegistryOptions,
  A2uiV1HostPlatform,
  A2uiV1FunctionCall,
  A2uiV1GenericRendererError,
  A2uiV1RendererCapabilities,
  A2uiV1RendererCapabilitiesOptions,
  A2uiV1RendererError,
  A2uiV1RendererFunctionResponse,
  A2uiV1RendererFunctionResponseEnvelope,
  A2uiV1RendererToAgentEnvelope,
  A2uiV1RendererToAgentEnvelopeKind,
  A2uiV1SurfaceState,
  A2uiSurfaceStoreOptions,
  A2uiV1EnvelopeParseOptions,
  A2uiV1SurfaceValidationPolicy,
  A2uiV1UpdateComponentsEnvelope,
  A2uiV1UpdateDataModelEnvelope,
  A2uiV1ValidationErrorCode,
  A2uiV1ValidationRendererError,
  ResolvedA2uiV1JsonlResource,
  A2uiV1ValidatedHostExtensionComponent,
} from "./v1/index.js";
