/**
 * Concise public names for the current A2UI profile.
 *
 * The package name supplies the A2UI context and the package root supplies the current supported
 * profile. Protocol versions remain explicit in wire values and compatibility documentation.
 */
export { A2uiParseError as ParseError, A2uiResourceError as ResourceError } from "./errors.js";
export { A2UI_MIME_TYPE as MIME_TYPE } from "./mime.js";
export type { A2uiResourceReader as ResourceReader } from "./mime.js";
export { A2UI_MCP_SCHEMA_REVISION as MCP_SCHEMA_REVISION } from "./schema-revision.js";
export {
  A2UI_MCP_BINDING_VERSION as MCP_BINDING_VERSION,
  A2UI_MCP_EXTENSION_CAPABILITIES as MCP_EXTENSION_CAPABILITIES,
  A2UI_MCP_EXTENSION_ID as MCP_EXTENSION_ID,
  A2UI_MCP_PROTOCOL_VERSION as MCP_PROTOCOL_VERSION,
  A2UI_MCP_TRANSPORT as MCP_TRANSPORT,
  isA2uiMcpBindingGrant as isMcpBindingGrant,
  negotiateA2uiMcpBinding as negotiateMcpBinding,
} from "./binding.js";
export type {
  A2uiMcpBindingGrant as McpBindingGrant,
  A2uiMcpBindingNegotiation as McpBindingNegotiation,
} from "./binding.js";
export {
  A2UI_V1_MAX_COMPONENTS as MAX_COMPONENTS,
  A2UI_V1_MAX_ENVELOPES as MAX_ENVELOPES,
  A2UI_V1_MAX_SURFACES as MAX_SURFACES,
  A2UI_V1_MAX_SOURCE_LENGTH as MAX_SOURCE_LENGTH,
  A2UI_V1_MAX_STORE_STRING_CODE_UNITS as MAX_STORE_STRING_CODE_UNITS,
  A2UI_V1_MAX_STORE_VALUES as MAX_STORE_VALUES,
  A2UI_V1_PROTOCOL_VERSION as PROTOCOL_VERSION,
  A2UI_V1_BASIC_CATALOG_ID as BASIC_CATALOG_ID,
  A2UI_V1_BASIC_COMPONENT_NAMES as BASIC_COMPONENT_NAMES,
  A2UI_V1_BASIC_FUNCTION_NAMES as BASIC_FUNCTION_NAMES,
  A2UI_V1_SYSTEM_FUNCTION_NAMES as SYSTEM_FUNCTION_NAMES,
  A2UI_V1_HOST_EXTENSION_MAX_EVENTS as HOST_EXTENSION_MAX_EVENTS,
  A2UI_V1_HOST_EXTENSION_MAX_INSTANCES as HOST_EXTENSION_MAX_INSTANCES,
  A2UI_V1_HOST_EXTENSION_MAX_MANIFESTS as HOST_EXTENSION_MAX_MANIFESTS,
  A2UI_V1_HOST_EXTENSION_MAX_NEEDS as HOST_EXTENSION_MAX_NEEDS,
  A2UI_V1_HOST_EXTENSION_MAX_UPDATES as HOST_EXTENSION_MAX_UPDATES,
  A2UI_V1_HOST_EXTENSION_PROFILE_ID as HOST_EXTENSION_PROFILE_ID,
  A2UI_V1_HOST_EXTENSION_PROFILE_VERSION as HOST_EXTENSION_PROFILE_VERSION,
  A2uiSurfaceStore as SurfaceStore,
  createA2uiV1ActionDeliveryHandler as createActionDeliveryHandler,
  createA2uiV1ActionEnvelope as createActionEnvelope,
  createA2uiV1BasicCatalogPolicy as createBasicCatalogPolicy,
  createA2uiV1HostExtensionCapabilitySettings as createHostExtensionCapabilitySettings,
  createA2uiV1HostExtensionRegistry as createHostExtensionRegistry,
  createA2uiV1RendererCapabilities as createRendererCapabilities,
  evaluateA2uiV1FormatString as evaluateFormatString,
  getA2uiV1HostExtensionCatalogIds as getHostExtensionCatalogIds,
  getA2uiV1HostExtensionManifest as getHostExtensionManifest,
  getA2uiV1HostExtensionManifestFingerprint as getHostExtensionManifestFingerprint,
  isA2uiV1HostExtensionRegistry as isHostExtensionRegistry,
  negotiateA2uiV1Capabilities as negotiateCapabilities,
  negotiateA2uiV1HostExtensions as negotiateHostExtensions,
  parseA2uiV1AgentCapabilities as parseAgentCapabilities,
  parseA2uiV1Envelope as parseEnvelope,
  parseA2uiV1HostExtensionCapabilityValue as parseHostExtensionCapabilityValue,
  parseA2uiV1HostExtensionManifest as parseHostExtensionManifest,
  parseA2uiV1Jsonl as parseJsonl,
  parseA2uiV1RendererCapabilities as parseRendererCapabilities,
  parseA2uiV1RendererToAgentEnvelope as parseRendererToAgentEnvelope,
  resolveA2uiV1JsonlFromToolResult as resolveJsonlFromToolResult,
  validateA2uiV1HostExtensionComponent as validateHostExtensionComponent,
  validateA2uiV1HostExtensionEvent as validateHostExtensionEvent,
  validateA2uiV1SurfaceState as validateSurfaceState,
} from "./v1/index.js";
export type {
  A2uiV1Action as Action,
  A2uiV1ActionDeliveryHandler as ActionDeliveryHandler,
  A2uiV1ActionDeliveryOptions as ActionDeliveryOptions,
  A2uiV1ActionDeliveryPolicy as ActionDeliveryPolicy,
  A2uiV1ActionEnvelope as ActionEnvelope,
  A2uiV1ActionEnvelopeInput as ActionEnvelopeInput,
  A2uiV1AgentCapabilities as AgentCapabilities,
  A2uiV1BasicCatalogPolicyOptions as BasicCatalogPolicyOptions,
  A2uiV1CallAgentFunctionEnvelope as CallAgentFunctionEnvelope,
  A2uiV1CapabilityNegotiation as CapabilityNegotiation,
  A2uiV1Component as Component,
  A2uiV1CreateSurfaceEnvelope as CreateSurfaceEnvelope,
  A2uiV1DeleteSurfaceEnvelope as DeleteSurfaceEnvelope,
  A2uiV1Envelope as Envelope,
  A2uiV1EnvelopeKind as EnvelopeKind,
  A2uiV1EnvelopeParseOptions as EnvelopeParseOptions,
  A2uiV1ErrorEnvelope as ErrorEnvelope,
  A2uiV1FormatStringExpressionBudgetConsumer as FormatStringExpressionBudgetConsumer,
  A2uiV1FormatStringExpressionResolver as FormatStringExpressionResolver,
  A2uiV1FunctionCall as FunctionCall,
  A2uiV1GenericRendererError as GenericRendererError,
  A2uiV1HostExtensionCapabilityEntry as HostExtensionCapabilityEntry,
  A2uiV1HostExtensionCapabilitySettings as HostExtensionCapabilitySettings,
  A2uiV1HostExtensionEventManifest as HostExtensionEventManifest,
  A2uiV1HostExtensionManifest as HostExtensionManifest,
  A2uiV1HostExtensionNegotiation as HostExtensionNegotiation,
  A2uiV1HostExtensionRegistry as HostExtensionRegistry,
  A2uiV1HostExtensionRegistryOptions as HostExtensionRegistryOptions,
  A2uiV1HostPlatform as HostPlatform,
  A2uiV1RendererCapabilities as RendererCapabilities,
  A2uiV1RendererCapabilitiesOptions as RendererCapabilitiesOptions,
  A2uiV1RendererError as RendererError,
  A2uiV1RendererFunctionResponse as RendererFunctionResponse,
  A2uiV1RendererFunctionResponseEnvelope as RendererFunctionResponseEnvelope,
  A2uiV1RendererToAgentEnvelope as RendererToAgentEnvelope,
  A2uiV1RendererToAgentEnvelopeKind as RendererToAgentEnvelopeKind,
  A2uiV1SurfaceState as SurfaceState,
  A2uiV1SurfaceValidationPolicy as SurfaceValidationPolicy,
  A2uiV1UpdateComponentsEnvelope as UpdateComponentsEnvelope,
  A2uiV1UpdateDataModelEnvelope as UpdateDataModelEnvelope,
  A2uiV1ValidatedHostExtensionComponent as ValidatedHostExtensionComponent,
  A2uiV1ValidationErrorCode as ValidationErrorCode,
  A2uiV1ValidationRendererError as ValidationRendererError,
  A2uiSurfaceStoreOptions as SurfaceStoreOptions,
  ResolvedA2uiV1JsonlResource as ResolvedJsonlResource,
} from "./v1/index.js";
